### ISSUE TITLE
Feature request: achievement checkall

### ISSUE THREAD

**Issue by icaca** [azerothcore/mod-eluna#105]
There is a ".achievement checkall" in the GM command.
Can this method be added to eluna to check the user's achievements?

**Comment by r-o-b-o-t-o** [comment]
You can use `[RunCommand](https://www.azerothcore.org/pages/eluna/Global/RunCommand.html)`

```lua
RunCommand("achievement checkall " .. playerName)
```

**Comment by 55Honey** [comment]
You can use https://www.azerothcore.org/pages/eluna/Player/HasAchieved.html and iterate over the achievement IDs that you need.

**Comment by icaca** [comment]
> You can also use https://www.azerothcore.org/pages/eluna/Player/HasAchieved.html and iterate over the achievement IDs that you need. Or https://www.azerothcore.org/pages/eluna/Player/GetAchievementCriteriaProgress.html and do the same for specific criteria.

".achievement checkall" can be used to check the achievement status of all achievements. If the achievement has actually been completed, but it is not displayed normally, this method will allow the player to get the achievement.
RunCommand has been tested and it does work.
