### ISSUE TITLE
Item:GetItemLink case server crash

### ISSUE THREAD

**Issue by icaca** [azerothcore/mod-eluna#112]
RegisterPlayerEvent(PLAYER_EVENT_ON_STORE_NEW_ITEM) is fired when the player creates a character. Try to use Item:GetItemLink, the server will restart without any log.

```
function OnLoot(event, player, item, count)
    print(item:GetItemLink(4))
end

RegisterPlayerEvent(53, OnLoot)

```

**Comment by 55Honey** [comment]
Always Null-check variables that might no have a value before accessing them.
Example:
```lua
function OnLoot(event, player, item, count)
    if item
        print(item:GetItemLink(4))
    else
        print("item was null")
    end
end

RegisterPlayerEvent(53, OnLoot)
```

Object variables are prone to that behaviour and it is on the programmer to catch it.

**Comment by icaca** [comment]
It has been judged, even if it is nil, it should report an error
