### ISSUE TITLE
Customized new hook: OnPlayerDamage

### ISSUE THREAD

**Issue by GoMateoGo** [azerothcore/mod-eluna#122]
Eluna:
![image](https://user-images.githubusercontent.com/18229643/230742462-c2ab63fb-447f-4c21-9ca9-eba7f6d6b1f6.png)

ScriptMgr:
![image](https://user-images.githubusercontent.com/18229643/230742487-694f2abc-f250-4a63-bfff-ae42d175fa54.png)

ElunaScript:
![image](https://user-images.githubusercontent.com/18229643/230742555-cfb3be9c-3b5f-4826-862c-238f3cd08a25.png)

Combat Log:
![image](https://user-images.githubusercontent.com/18229643/230742547-26ce55d0-3b1a-43d9-ae58-a01e6bda844e.png)

Perhaps it was an eluna hook encoding error
In fact, the amount of health removed by the victim was after the change. However, the client displays before the change

**Comment by 55Honey** [comment]
See https://github.com/azerothcore/azerothcore-wotlk/issues/15893
Your custom implementation does it wrong.
