### ISSUE TITLE
error compiling with latest AC update

### ISSUE THREAD

**Issue by Tony931023** [azerothcore/mod-eluna#128]
f8cce45e8a5b49f63c413ed250acf3f84b7ebd24

In file included from /mnt/hdd/am-code/modules/mod-eluna/src/LuaEngine/LuaFunctions.cpp:23:
/mnt/hdd/am-code/modules/mod-eluna/src/LuaEngine/UnitMethods.h:1208:31: fatal error: no member named 'name' in 'ChrRacesEntry'; did you mean 'Name'?
        Eluna::Push(L, entry->name[locale]);
                              ^~~~
                              Name
/mnt/hdd/am-code/src/server/shared/DataStores/DBCStructure.h:701:17: note: 'Name' declared here
    char const* Name[16];                                   // 14-29
                ^
1 error generated.
make[2]: *** [modules/CMakeFiles/modules.dir/build.make:297: modules/CMakeFiles/modules.dir/mod-eluna/src/LuaEngine/LuaFunctions.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....

**Comment by wefgame** [comment]
I confirm that I also encountered this problem
