### ISSUE TITLE
:660:65: fatal error: non-virtual member function marked 'override' hides virtual member function

### ISSUE THREAD

**Issue by souloi** [azerothcore/mod-eluna#132]
/home/ubuntu/azerothcore/modules/mod-eluna/src/ElunaLuaEngine_SC.cpp:660:65: fatal error: non-virtual member function marked 'override' hides virtual member function
    void OnGiveXP(Player* player, uint32& amount, Unit* victim) override
                                                                ^
/home/ubuntu/azerothcore/src/server/game/Scripting/ScriptMgr.h:1038:18: note: hidden overloaded virtual function 'PlayerScript::OnGiveXP' declared here: different number of parameters (4 vs 3)
    virtual void OnGiveXP(Player* /*player*/, uint32& /*amount*/, Unit* /*victim*/, uint8 /*xpSource*/) { }
                 ^
1 error generated.
make[2]: *** [modules/CMakeFiles/modules.dir/build.make:154: modules/CMakeFiles/modules.dir/mod-eluna/src/ElunaLuaEngine_SC.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1287: modules/CMakeFiles/modules.dir/all] Error 2

**Comment by r-o-b-o-t-o** [comment]
Hello, this should be fixed with the latest commit. Please pull the latest mod-eluna and try again.

**Comment by souloi** [comment]
ok
