### ISSUE TITLE
CREATURE_EVENT_ON_DIED for RegisterCreatureEvent not working on reload

### ISSUE THREAD

**Issue by 0xCiBeR** [azerothcore/mod-eluna#139]
The event CREATURE_EVENT_ON_DIED(ID 4) for RegisterCreatureEvent is no triggered if added to a script and then you reload eluna.

It only starts to work after you restart the server

Steps to reproduce:
1.) on a running server, create a lua script that uses the RegisterCreatureEvent and the CREATURE_EVENT_ON_DIED(ID 4) event.
2.) reload eluna using .reload eluna and try to kill the creature you referenced in the RegisterCreatureEvent

**Comment by 55Honey** [comment]
You need to reset a creature to trigger the new AI.
You can e.g. spawn a new one temporarily or kill it twice, then it will trigger in the second kill.
