### ISSUE TITLE
Why does error LNK2019: unresolved external symbol 'void __cdecl Addmod_eluna_masterScripts (void)' appear

### ISSUE THREAD

**Issue by qiuyu123456** [azerothcore/mod-eluna#145]
Why does error LNK2019: unresolved external symbol 'void __cdecl Addmod_eluna_masterScripts (void)' appear

**Comment by r-o-b-o-t-o** [comment]
Remove `-master` from your folder name, then rerun CMake and build.
Better yet, use `git clone` instead of downloading the zip from GitHub's website :)
