### ISSUE TITLE
Can add feature Player::GetAchievementPoint ?

### ISSUE THREAD

**Issue by kissingers** [azerothcore/mod-eluna#159]
Every player can see achievement point, but It's hard to get if use database or a specific achievement to accumulate, but I think it must have a place have already calculate and store the point on server. So if can  return GetAchievementPoint hock? then I can do much things abuout total achievementpoint.

**Comment by worldofd2** [comment]
I have a PR regarding Player:GetAchievementPoints and Player:GetCompletedAchievementsCount, the second can include or exclude Feats of Strength, default is exclude.

**Comment by kissingers** [comment]
> I have a PR regarding Player:GetAchievementPoints and Player:GetCompletedAchievementsCount, the second can include or exclude Feats of Strength, default is exclude.

Thanks, I try add to my eluna code and test.

**Comment by worldofd2** [comment]
PR was approved and now implemented. [#158](https://github.com/azerothcore/mod-eluna/pull/158)
