### ISSUE TITLE
RegisterCreatureEvent not working for script AI boss

### ISSUE THREAD

**Issue by kissingers** [azerothcore/mod-eluna#170]
Try test , will find the RegisterCreatureEvent not working any more. not only methed 9 , but all can not.

-- .go c 76586

local function OnDamageTaken(event, creature, attacker, damage)
	creature:SendUnitSay("Test")
end
RegisterCreatureEvent(21878, 9, OnDamageTaken)

**Comment by 55Honey** [comment]
You can not use 2 AIs for Unit in parallel. If a creature has a .cpp script, it will use it instead of any Lua AI. If a creature has SAI, it will use SAI until it respawns. Then switch to Lua *instead* of SAI.

**Comment by kissingers** [comment]
Thanks, I see , so something must register to word even or player even to replace the boss LUA AI
