### ISSUE TITLE
Error When Compiling Azerothcore.

### ISSUE THREAD

**Issue by Dranos-Nupper** [azerothcore/mod-eluna#184]
![image](https://github.com/azerothcore/mod-eluna/assets/6026902/7684e939-9b52-40f5-a6c3-ccb712f17ac8)

**Comment by 55Honey** [comment]
Update both your core and the Eluna module.
If else fails, provide revisions for both.

**Comment by Nupper** [comment]
This is my first day with azerothcore so everything should be latest...but i might made mistake so i will double check.

**Comment by Dranos-Nupper** [comment]
i appear to be using [liyunfan1223/azerothcore-wotlk/tree/Playerbot](https://github.com/liyunfan1223/azerothcore-wotlk/tree/Playerbot). due to the standard way pumping out to many errors for Playerbot.

**Comment by 55Honey** [comment]
mod-playerbots is not compatible at all with master. You most certainly need to use liyunfan's fork to make it work at all.
This fork of AC might not be updated to work with the latest eluna. You can roll back Eluna to a previous commit and try again. But there's no support for forks of AC.
