### ISSUE TITLE
Compile issues as of latest Eluna Module update

### ISSUE THREAD

**Issue by angrytoilet** [azerothcore/mod-eluna#36]
Error(s):

Error	C2061	syntax error: identifier 'EvadeReason' (compiling source file C:\AzerothCore\Source\azerothcore-wotlk\modules\mod-eluna\src\LuaEngine\LuaEngine.cpp)	modules	C:\AzerothCore\Source\azerothcore-wotlk\modules\mod-eluna\src\LuaEngine\ElunaCreatureAI.h	157	

Error (active)	E2500	a literal operator template must have a template parameter list equivalent to '<char ...>'	modules	C:\AzerothCore\Source\azerothcore-wotlk\deps\fmt\include\fmt\format.h	3030
	
Error (active)	E1455	member function declared with 'override' does not override a base class member	modules	C:\AzerothCore\Source\azerothcore-wotlk\modules\mod-eluna\src\LuaEngine\ElunaCreatureAI.h	157	

Error (active)	E0020	identifier "EvadeReason" is undefined	modules	C:\AzerothCore\Source\azerothcore-wotlk\modules\mod-eluna\src\LuaEngine\ElunaCreatureAI.h	157

**Comment by 55Honey** [comment]
What's your AC revision?
