### ISSUE TITLE
Player:ResetPetTalents()  will case worldsever error shutdown

### ISSUE THREAD

**Issue by kissingers** [azerothcore/mod-eluna#51]
when I use lua Player:ResetPetTalents() ,the server down. but 6mouth before it has no problem.
I try use game NPC that training the hunter to reset pet's talent, the server ok.

**Comment by 55Honey** [comment]
Confirmed:
![image](https://user-images.githubusercontent.com/71938210/177365811-aeeebd29-b4fd-4c48-8b1b-066ad7cecf3d.png)

**Comment by kissingers** [comment]
the error code are same as the picture, which  source code are at  pet.cpp 
When use '.reset talents', server are ok, but use the lua, the sever down, so might server change the code, and eluna not suite for the new code.

**Comment by 55Honey** [comment]
![image](https://user-images.githubusercontent.com/71938210/184525796-9b1c3c00-ccfe-4972-9b76-88564d991432.png)
Can not reproduce anymore. Thanks @Nefertumm for looking into it.
If it keeps happening for you, please provide details about your environment and comment here @kissingers .
