### ISSUE TITLE
Player Hook 45 - Achievement seem to cause segfault often, but not always

### ISSUE THREAD

**Issue by georgzoeller** [azerothcore/mod-eluna#57]
Commit: bad5bb7e253ae86b85a50464ad8dfe4d28201d80

I am encountering segvaults when hooking player event 45 to trigger an HTTP request.

It's no 100%, but 90% of the time when an achievement is triggered the server dies which is very unfortunate because loot gets lost on any major dungeon achievement. Unhooking removes the crash.

Didn't get a chance to debug build and investigate yet.

```
local function OnPlayerAchievementComplete (event, player, achievement)
  if (achievement ~= nil and achievement:GetId() ~= 0) then
   
  // HttpRequest(....)

  end
end

RegisterPlayerEvent(45, OnPlayerAchievementComplete)
```

**Comment by 55Honey** [comment]
Hi georgzoeller,
thanks for the report. Any further clarification would be appreciated. Does the segfault happen in the event regardless of what's executed? Or only for a HTTP request?

Debugging it would be ace, thanks!

**Comment by georgzoeller** [comment]
Spent some more time testing by using .achievement add

- Doesn't happen with hook is not hooked
- Doesn't happen on an empty hook
- Does happen about 3/5 times when hook contains a http request
- Does not seem to happen on http requests in other hooks as far as I can tell - I hooked a large number of events and sent http requests from them but the only time I got the segvault is from the achievement hook.
- The only achievement specific function I'm using is achievement:GetId() consuming the achievement arg passed into the hook.

**Comment by 55Honey** [comment]
Thanks for the followup! Feel free to add any further input.

**Comment by 55Honey** [comment]
Any news on this @georgzoeller ?
Did it happen again? Can you provide a crashlog?

**Comment by kncxstudio** [comment]
It's also happend on latest AzerothCore.
commit rev: https://github.com/azerothcore/azerothcore-wotlk/commit/bd7f139bb8861e4c89651017b2371b9fa035a4a5

Encounter segvaults when hooking player event 45 to trigger an HTTP request.

**Comment by 55Honey** [comment]
To be able to look into it, we need to reproduce it. Please provide the revisions of AC, mod-Eluna and the script with reproduction steps.

**Comment by kncxstudio** [comment]
AC:https://github.com/azerothcore/azerothcore-wotlk/commit/bd7f139bb8861e4c89651017b2371b9fa035a4a5
mod-Eluna:https://github.com/azerothcore/mod-eluna/commit/53514a228b16894f68c80f2c922e5233975cd06b

reproduce:
`local function OnPlayerAchievementComplete (event, player, achievement)
  if (achievement ~= nil and achievement:GetId() ~= 0) then
   
  // HttpRequest(....)

  end
end

RegisterPlayerEvent(45, OnPlayerAchievementComplete)`

.achievement add in game and trigger this hook. It will be reproduced in 10 times.
