### ISSUE TITLE
Reload message should be sent only to GMs

### ISSUE THREAD

**Issue by 55Honey** [azerothcore/mod-eluna#61]
https://github.com/azerothcore/mod-eluna/blob/684eb0335bacc81110e75e36830204dea90c45c3/src/LuaEngine/LuaEngine.cpp#L136

There should be a check here to forward this message only to GM accounts and the console since it keeps confusing players.

**Comment by heyitsbench** [comment]
Don't know if I'm missing something, but replacing `SendServerMessage` with `SendGMText` [doesn't send it to players with a GM level of 0.](https://user-images.githubusercontent.com/38561765/197870803-4effe969-84f8-45c4-8883-5b1ceaefaf3d.png) So if that's a suitable fix, I can submit a PR, maybe tie it to a config option.

**Comment by 55Honey** [comment]
Sounds exactly what we're looking for. Please do 🙏 
Thanks!
