### ISSUE TITLE
error compiling lua

### ISSUE THREAD

**Issue by Tony931023** [azerothcore/mod-eluna#70]
In file included from /mnt/hdd/amanthul-azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/LuaFunctions.cpp:23:
/mnt/hdd/amanthul-azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/UnitMethods.h:2997:30: fatal error: no member named 'modifyThreatPercent' in 'ThreatMgr'; did you mean 'ModifyThreatByPercent'?
        unit->GetThreatMgr().modifyThreatPercent(victim, threatPct);
                             ^~~~~~~~~~~~~~~~~~~
                             ModifyThreatByPercent
/mnt/hdd/amanthul-azerothcore-wotlk/src/server/game/Combat/ThreatMgr.h:220:10: note: 'ModifyThreatByPercent' declared here
    void ModifyThreatByPercent(Unit* victim, int32 percent);
         ^
1 error generated.
make[2]: *** [modules/CMakeFiles/modules.dir/build.make:544: modules/CMakeFiles/modules.dir/mod-eluna/src/LuaEngine/LuaFunctions.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1218: modules/CMakeFiles/modules.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by 55Honey** [comment]
Please update your mod-eluna.
https://github.com/azerothcore/mod-eluna/blob/bfd3bda8b94c5416c6590a238d88fc5f30030f6f/src/LuaEngine/UnitMethods.h#L2997

**Comment by Tony931023** [comment]
@55Honey Thanks
