### ISSUE TITLE
Unit:SendUnitSay does not work

### ISSUE THREAD

**Issue by ihardyslide** [azerothcore/mod-eluna#71]
Hi,

I am using the docker way of setting up Azerothcore with the current version and installed this eluna module, also with current version.
Everything seems to be working great, except that [Unit:SendUnitSay()](https://elunaluaengine.github.io/Unit/SendUnitSay.html) seems to be not working.

I have this example script:
```local PLAYER_EVENT_ON_RESURRECT = 36

local function OnPlayerResurrected(event, player)
    local creaturesInRange = player:GetCreaturesInRange(200, 29445)
    for key, unit in pairs(creaturesInRange) do
        if (unit:GetName() == "Thorim") then
            unit:SendUnitYell("Wie kann das sein?!", 0)
            unit:SendUnitSay("Wie kann das sein?!", 0)
            unit:SendUnitSay("Offenbar seid ihr wohl stärker als ich dachte.", 0)
            unit:SendUnitWhisper("Offenbar seid ihr wohl stärker als ich dachte.", 0, player)
            unit:SendUnitWhisper("Wohlmöglich könntet ihr mir bei einer Sache helfen?", 0, player)
            unit:SendUnitWhisper("Keine Zeit für Fragen! Wenn ihr bereit seid, müsst ihr mich bloß annicken.", 0, player)
        end
    end
end

RegisterPlayerEvent(PLAYER_EVENT_ON_RESURRECT, OnPlayerResurrected)
```

As you can see in this screenshot, yelling and whispering works, but say does not.

![image](https://user-images.githubusercontent.com/1192287/200660806-8e811ea1-016a-48b1-9317-5f2178e66f1c.png)

I didn't find anything related to this, so that's why I am posting this.

BR & Thanks in advance

**Comment by 55Honey** [comment]
Thanks for the issue.
I can not reproduce this.

```lua
local function command( event, player, command, chathandler )
    player:SendUnitSay('Player says this.', 0)
    if player:GetSelection() then
        player:GetSelection():SendUnitSay('Selection says this.', 0)
    else
        player:SendUnitSay('No Selection', 0)
    end
end
RegisterPlayerEvent(42, command)
```

Using the above script and doing `.tele durotar`.
Target the goblin Rezlak and type `.asdf` or any non-existing command.
See how it is printed in chat as well as in a say-bubble.
Target the Elder-Mottled Boar nearby and use `.asdf` again.
The say is only printed in chat.

**Comment by r-o-b-o-t-o** [comment]
Cannot reproduce either:
![image](https://user-images.githubusercontent.com/24357633/221998562-84b5dbd7-d12c-4a59-9fe7-7e91b8c27ece.png)
