### ISSUE TITLE
fresh pull

### ISSUE THREAD

**Issue by 0xdeadbeef** [azerothcore/mod-eluna#92]
i did a fresh pull of azerothcore and mod-eluna got  undefined reference to `OPvPCapturePointNA::GetControllingFaction() const' while trying to compile
../../../modules/libmodules.a(LuaFunctions.cpp.o): in function `LuaGlobalFunctions::GetOwnerHalaa(lua_State*)':
/home/fcastle/azerothcore-wotlk/modules/mod-eluna/src/LuaEngine/GlobalMethods.h:3363: undefined reference to `OPvPCapturePointNA::GetControllingFaction() const'

**Comment by 55Honey** [comment]
Please post your core revision and mod-Eluna revision.

**Comment by 0xdeadbeef** [comment]
master on both ,i got past it by just leaving to to default and compiling its setting to dynamic(so files that screwed me)

**Comment by 55Honey** [comment]
Revision refers to which set of commits you have pulled. As of now, the latest AC would be c3dd1b7a5ca0a9945d609213fdd3c4a19e0106e2
But "latest" changes several times a day usually.

I take it your issue is resolved? Feel free to close it, if so.
