### ISSUE TITLE
PLAYER_EVENT_ON_CHANNEL_CHAT channel argument invalid

### ISSUE THREAD

**Issue by 0xCiBeR** [azerothcore/mod-eluna#98]
When using PLAYER_EVENT_ON_CHANNEL_CHAT event(ID: 22) it has the following arguments:
**(event, player, msg, Type, lang, channel)**

The channel argument/variable is always 0 instead of the real channel ID that is stored in the db.
Not sure if this should be channel name, or ID. I think ID makes more sense as there can be multiple channels with the same name.

**Comment by 55Honey** [comment]
Good catch! Thanks for the report.

https://github.com/azerothcore/mod-eluna/blob/53514a228b16894f68c80f2c922e5233975cd06b/src/LuaEngine/PlayerHooks.cpp#L512

It seems like a core issue to me, cause the id is requested by mod-Eluna.
