### ISSUE TITLE
Feature request: expose OnGroupRollRewardItem player event

### ISSUE THREAD

**Issue by icaca** [azerothcore/mod-eluna#99]
In PlayerScript, there are OnLootItem, OnStoreNewItem, OnCreateItem, OnQuestRewardItem, OnGroupRollRewardItem methods, but only PLAYER_EVENT_ON_LOOT_ITEM = 32 is found in RegisterPlayerEvent. Is there a corresponding serial number for OnStoreNewItem, OnCreateItem, OnQuestRewardItem, OnGroupRollRewardItem? If not, can it be increased?

**Comment by r-o-b-o-t-o** [comment]
Not sure what you are referring to, but the event IDs can be found on the [online documentation](https://www.azerothcore.org/pages/eluna/Global/RegisterPlayerEvent.html).

**Comment by icaca** [comment]
You are right, I was looking at https://elunaluaengine.github.io/Global/RegisterPlayerEvent.html.

**Comment by icaca** [comment]
OnGroupRollRewardItem not found

**Comment by 55Honey** [comment]
Feel free to expose events/hooks, which currently do not exist in mod-eluna.
